#### регистрация покупателя

POST http://127.0.0.1:8000/api/v1/user/register
Content-Type: application/json

{
    "first_name": "Alisia",
    "last_name": "Sebas",
    "email": "vlad@mail.ru",
    "password": "12345",
    "company": "ООО_Лидер",
    "position": "Менеджер"   
}


##### Авторизация
POST http://127.0.0.1:8000/api/v1/user/login
Content-Type: application/json


{
    "email": "vlad@mail.ru",
    "password": "12345"
}


##### Подтверждение почтового адреса
POST http://127.0.0.1:8000/api/v1/user/register/confirm
Content-Type: application/json

{
    "email": "vlad@mail.ru",
    "token": "2b715bb2e62a86e127"  
}


#### Сигнал на добавления товара поставщика
POST http://127.0.0.1:8000/api/v1/partner/update
Content-Type: application/json
Authorization: Token db7106206ba8b0d179ebd83e9ef426d749e57662


##### Получение информации о пользователе
GET  http://127.0.0.1:8000/api/v1/account/info
Content-Type: application/json
Authorization: Token db7106206ba8b0d179ebd83e9ef426d749e57662

##### Изменение информации о пользователе
POST http://127.0.0.1:8000/api/v1/account/info
Content-Type: application/json
Authorization: Token db7106206ba8b0d179ebd83e9ef426d749e57662

{
    "position": "Владелец" 
}


##### Просмотр статуса магазина
GET http://127.0.0.1:8000/api/v1/partner/state
Content-Type: application/json
Authorization: Token db7106206ba8b0d179ebd83e9ef426d749e57662

##### Изменение статуса магазина
POST http://127.0.0.1:8000/api/v1/partner/state
Content-Type: application/json
Authorization: Token db7106206ba8b0d179ebd83e9ef426d749e57662

{
    "state": "True"
}

##### Список категорий
GET http://127.0.0.1:8000/api/v1/categories
Content-Type: application/json

##### Список магазинов
GET http://127.0.0.1:8000/api/v1/shops
Content-Type: application/json

##### Список товара
GET http://127.0.0.1:8000/api/v1/products
Content-Type: application/json

{
    "shop_id": "1",
    "category_id": "224"  
}

##### Создание корзины
POST http://127.0.0.1:8000/api/v1/basket
Content-Type: application/json
Authorization: Token 7c7d54442ba7ba2a62d8e420f3552acbc3ba6eba

{
   "items": [{ "product_info": 18,
              "quantity": 3}]
}

##### Удаление элементов корзины
DELETE http://127.0.0.1:8000/api/v1/basket
Content-Type: application/json
Authorization: Token db7106206ba8b0d179ebd83e9ef426d749e57662

{
   "items": "15"
}

##### Просмотр элементов корзины
GET http://127.0.0.1:8000/api/v1/basket
Content-Type: application/json
Authorization: Token 7c7d54442ba7ba2a62d8e420f3552acbc3ba6eba

##### Добавление элементов в корзину
PUT http://127.0.0.1:8000/api/v1/basket
Content-Type: application/json
Authorization: Token 7c7d54442ba7ba2a62d8e420f3552acbc3ba6eba

{
   "items": [{ "id": 13,
              "quantity": 1},
              { "id": 14,
              "quantity": 1}]
}


##### Создание контакта пользователя
POST http://127.0.0.1:8000/api/v1/contact
Content-Type: application/json
Authorization: Token 7c7d54442ba7ba2a62d8e420f3552acbc3ba6eba

{
    "city": "Sochi",
    "street": "Streegt",
    "phone": "82473386677"
}

##### Удаление информации о контактных данных пользователя
DELETE  http://127.0.0.1:8000/api/v1/contact
Content-Type: application/json
Authorization: Token db7106206ba8b0d179ebd83e9ef426d749e57662

{
   "items": "1"
}

##### Изменения контактных данных пользователя
PUT  http://127.0.0.1:8000/api/v1/contact
Content-Type: application/json
Authorization: Token 7c7d54442ba7ba2a62d8e420f3552acbc3ba6eba

{
    "id": "3",
    "city": "Moscow",
    "street": "Okt",
    "phone": "82478286676",
    "house": "My"
}

##### Получение контактов пользователя
GET http://127.0.0.1:8000/api/v1/contact
Content-Type: application/json
Authorization: Token 7c7d54442ba7ba2a62d8e420f3552acbc3ba6eba

##### Просмотр заказа(История заказов)
GET http://127.0.0.1:8000/api/v1/order_confirm
Content-Type: application/json
Authorization: Token 7c7d54442ba7ba2a62d8e420f3552acbc3ba6eba

##### Подтверждение статуса заказа
POST http://127.0.0.1:8000/api/v1/order_confirm
Content-Type: application/json
Authorization: Token 7c7d54442ba7ba2a62d8e420f3552acbc3ba6eba

{
    "id": "6",
    "contact": "4"  
}

##### Изменение статуса заказа поставщиком
PUT http://127.0.0.1:8000/api/v1/order_confirm
Content-Type: application/json
Authorization: Token db7106206ba8b0d179ebd83e9ef426d749e57662

{
    "id": "6",
    "state": "confirmed"  
}
